[package]
name = "jincr"
version = "0.0.1"
edition = "2024"

[dependencies]
chrono = "0.4.43"
dotenv = "0.15.0"
jvars = "0.2.1"
serde_json = "1.0.149"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
